$(EXAMPLE_1_NAME):
	$(MAKE) -C SimplePointAdder $(EXAMPLE_1_NAME)

$(EXAMPLE_2_NAME):
	$(MAKE) -C SimplePointConstructor $(EXAMPLE_2_NAME)

$(EXAMPLE_3_NAME):
	$(MAKE) -C SimplePointInside $(EXAMPLE_3_NAME)

$(EXAMPLE_4_NAME):
	$(MAKE) -C ConvexPointConstructor $(EXAMPLE_4_NAME)

$(EXAMPLE_5_NAME):
	$(MAKE) -C ConvexPointAdder $(EXAMPLE_5_NAME)

$(EXAMPLE_6_NAME):
	$(MAKE) -C ConvexPointInside $(EXAMPLE_6_NAME)

$(EXAMPLE_7_NAME):
	$(MAKE) -C GeneralSegmentsAndBeam $(EXAMPLE_7_NAME)

clean:
	$(MAKE) -C SimplePointAdder clean
	$(MAKE) -C SimplePointConstructor clean
	$(MAKE) -C SimplePointInside clean