$(EXAMPLE_1_NAME):
	$(MAKE) -C SimplePointAdder $(EXAMPLE_1_NAME)

$(EXAMPLE_2_NAME):
	$(MAKE) -C SimplePointConstructor $(EXAMPLE_2_NAME)

$(EXAMPLE_3_NAME):
	$(MAKE) -C SimplePointInside $(EXAMPLE_3_NAME)

$(EXAMPLE_4_NAME):
	$(MAKE) -C ConvexPointConstructor $(EXAMPLE_4_NAME)

$(EXAMPLE_5_NAME):
	$(MAKE) -C ConvexPointAdder $(EXAMPLE_5_NAME)

$(EXAMPLE_6_NAME):
	$(MAKE) -C ConvexPointInside $(EXAMPLE_6_NAME)

$(EXAMPLE_7_NAME):
	$(MAKE) -C GeneralSegmentsAndBeam $(EXAMPLE_7_NAME)

$(EXAMPLE_8_NAME):
	$(MAKE) -C SimpleSegmentsAndBeam $(EXAMPLE_8_NAME)

$(EXAMPLE_9_NAME):
	$(MAKE) -C GeneralPointInside $(EXAMPLE_9_NAME)

$(EXAMPLE_10_NAME):
	$(MAKE) -C GeneralCurvesGeneral $(EXAMPLE_10_NAME)

$(EXAMPLE_11_NAME):
	$(MAKE) -C GeneralCurvesErmit $(EXAMPLE_11_NAME)

$(EXAMPLE_12_NAME):
	$(MAKE) -C ConvexPointConstructorJarvis $(EXAMPLE_12_NAME)

$(EXAMPLE_13_NAME):
	$(MAKE) -C ConvexIntersect $(EXAMPLE_13_NAME)

$(EXAMPLE_14_NAME):
	$(MAKE) -C GeneralCurvesBezier $(EXAMPLE_14_NAME)

$(EXAMPLE_15_NAME):
	$(MAKE) -C GeneralCurvesBezierFire $(EXAMPLE_15_NAME)

clean:
	$(MAKE) -C SimplePointAdder clean
	$(MAKE) -C SimplePointConstructor clean
	$(MAKE) -C SimplePointInside clean
	$(MAKE) -C ConvexPointConstructor clean
	$(MAKE) -C ConvexPointAdder clean
	$(MAKE) -C ConvexPointInside clean
	$(MAKE) -C GeneralSegmentsAndBeam clean
	$(MAKE) -C SimpleSegmentsAndBeam clean
	$(MAKE) -C GeneralPointInside clean
	$(MAKE) -C GeneralCurvesGeneral clean
	$(MAKE) -C GeneralCurvesErmit clean
	$(MAKE) -C ConvexPointConstructorJarvis clean
	$(MAKE) -C ConvexIntersect clean
	$(MAKE) -C GeneralCurvesBezier clean
	$(MAKE) -C GeneralCurvesBezierFire clean