clean:
	$(MAKE) -C SimplePointAdder clean
	$(MAKE) -C SimplePointConstructor clean
	$(MAKE) -C SimplePointInside clean
	$(MAKE) -C ConvexPointConstructor clean
	$(MAKE) -C ConvexPointAdder clean
	$(MAKE) -C ConvexPointInside clean
	$(MAKE) -C GeneralSegmentsAndBeam clean
	$(MAKE) -C SimpleSegmentsAndBeam clean