$(RENDER_LIB_NAME):
	$(MAKE) -C Render $(RENDER_LIB_NAME)

$(DRAW_LIB_NAME):
	$(MAKE) -C SDL $(DRAW_LIB_NAME)

$(POLYGON_LIB_NAME):
	$(MAKE) -C Polygon $(POLYGON_LIB_NAME)

$(SEGMENTS_LIB_NAME):
	$(MAKE) -C Segments $(SEGMENTS_LIB_NAME)

clean:
	$(MAKE) -C Render clean
	$(MAKE) -C SDL clean
	$(MAKE) -C Polygon clean
	$(MAKE) -C Segments clean